schema_version: 1

context:
  name: mimesis
  version: "19.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 63506622966a377757118408157e9c6f8f6ae1745a978207f6db516bb48c021c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - mimesis
        - mimesis.builtins
        - mimesis.providers
      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE
  summary: Mimesis is a robust data generator for Python that can produce a wide range of fake data in multiple languages.
  homepage: https://github.com/lk-geimfari/mimesis
  repository: https://github.com/lk-geimfari/mimesis
  documentation: https://mimesis.readthedocs.io/

extra:
  recipe-maintainers:
    - utabe
    - janjagusch
